{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bkash.flutter_module_demo",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3246982,
          "sha512": "e48a8d3ff402c1a1a3d5389da7e34eeb5d84c2d9462827e4b0e57e0dfd18abc2a75eec7256f6cf6cd681f3a18dbd1284508a3c59483a402820f7651544680e96",
          "sha256": "df18a8dc234388ff474af2ec330776bc54491ea632f5836484e4908c6254153d",
          "sha1": "f4149c25c6f39aaa8717ce7a290902040ea57fee",
          "md5": "7002b46eb4c4e3041bcdc53d7b4fbcf1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3246982,
          "sha512": "e48a8d3ff402c1a1a3d5389da7e34eeb5d84c2d9462827e4b0e57e0dfd18abc2a75eec7256f6cf6cd681f3a18dbd1284508a3c59483a402820f7651544680e96",
          "sha256": "df18a8dc234388ff474af2ec330776bc54491ea632f5836484e4908c6254153d",
          "sha1": "f4149c25c6f39aaa8717ce7a290902040ea57fee",
          "md5": "7002b46eb4c4e3041bcdc53d7b4fbcf1"
        }
      ]
    }
  ]
}
