{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bkash.flutter_module_demo",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 203424,
          "sha512": "e38dbc8f910a21bd81aadf2240eedd854daaefc626665ed561383ced688341920fa2845e5145d0a5b3764e7dbe2b916a6bd57917bb5621ce42c25ec8b81fc2d7",
          "sha256": "d7bac4b6b680cdc505acdcaf65d5d4abfd93d345fa67e556503962229875ca61",
          "sha1": "805acc807fcf5a9fb9fc9507b464bbe2f0e84f2e",
          "md5": "5bd57a38b8b58de85cb7cfd9375fd3ca"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 203424,
          "sha512": "e38dbc8f910a21bd81aadf2240eedd854daaefc626665ed561383ced688341920fa2845e5145d0a5b3764e7dbe2b916a6bd57917bb5621ce42c25ec8b81fc2d7",
          "sha256": "d7bac4b6b680cdc505acdcaf65d5d4abfd93d345fa67e556503962229875ca61",
          "sha1": "805acc807fcf5a9fb9fc9507b464bbe2f0e84f2e",
          "md5": "5bd57a38b8b58de85cb7cfd9375fd3ca"
        }
      ]
    }
  ]
}
