// Autogenerated from Pigeon (v4.2.15), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class Employee {
  Employee({
    this.name,
  });

  String? name;

  Object encode() {
    return <Object?>[
      name,
    ];
  }

  static Employee decode(Object result) {
    result as List<Object?>;
    return Employee(
      name: result[0] as String?,
    );
  }
}

class _PigeonFlutterApiCodec extends StandardMessageCodec {
  const _PigeonFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is Employee) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return Employee.decode(readValue(buffer)!);
      
      default:

        return super.readValueOfType(type, buffer);
      
    }
  }
}

abstract class PigeonFlutterApi {
  static const MessageCodec<Object?> codec = _PigeonFlutterApiCodec();

  void setEmployee(Employee emp);

  static void setup(PigeonFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.PigeonFlutterApi.setEmployee', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.PigeonFlutterApi.setEmployee was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Employee? arg_emp = (args[0] as Employee?);
          assert(arg_emp != null, 'Argument for dev.flutter.pigeon.PigeonFlutterApi.setEmployee was null, expected non-null Employee.');
          api.setEmployee(arg_emp!);
          return;
        });
      }
    }
  }
}
